### ISSUE TITLE
radxa rock 4cplus does not boot

### ISSUE THREAD

**Issue by fsgh42** [siderolabs/sbc-rockchip#40]
I have a couple of devices here I bought because the `talos` website [lists them as compatible](https://www.talos.dev/v1.9/talos-guides/install/single-board-computers/rock4cplus/) and they don't boot.

I used my own manifest like this (as the official ones seem to be unknown, see below):
```yaml
customization:
  extraKernelArgs:
    - gfxmode=1280x1024
    - net.ifnames=0
    - siderolink.api=https://sl.example.com/?jointoken=someToken
    - talos.events.sink=[someipv6::1]:10080
    - talos.logging.kernel=tcp://[someipv6::1]:8092
  meta:
    - key: 12
      value: |-
        "machineLabels":
          "omni.example.com/cluster": "clusterName"
          "omni.example.com/env": "testing"
  systemExtensions:
    officialExtensions:
      - siderolabs/amd-ucode
      - siderolabs/fuse3
      - siderolabs/intel-ucode
      - siderolabs/iscsi-tools
      - siderolabs/tailscale
      - siderolabs/util-linux-tools
overlay:
  image: siderolabs/sbc-rockchip
  name: rock4cplus
```
I tried setting and leaving out different options, but no luck. When flashing the image to SDcard and turning on the device, the power LED lights up, but that is it. Using the official `debian` based image from [here](https://github.com/radxa-build/rock-4c-plus) I was able to rule out card or hardware failure, as it boots and works just fine. 

So I can only assume it is some sort of bootloader problem and I am trying to figure out how I might be able to fix that, but I am not familiar with the build process for overlays at all - so any help is welcome.

Another user reported this as broken as well (see [slack](https://taloscommunity.slack.com/archives/CMARMBC4E/p1733586118142169)) and said there is no debug output on the serial port whatsoever (which I don't happen to have the required hardware for).

_btw_: The image hash referenced in the docs don't seem to exist:
```
$ curl -L https://factory.talos.dev/image/ed7091ab924ef1406dadc4623c90f245868f03d262764ddc2c22c8a19eb37c1c/v1.9.0-alpha.0/metal-arm64.raw.xz
schematic ID "ed7091ab924ef1406dadc4623c90f245868f03d262764ddc2c22c8a19eb37c1c" not found
$ curl -L https://factory.talos.dev/image/ed7091ab924ef1406dadc4623c90f245868f03d262764ddc2c22c8a19eb37c1c/v1.8.3/metal-arm64.raw.xz
schematic ID "ed7091ab924ef1406dadc4623c90f245868f03d262764ddc2c22c8a19eb37c1c" not found
```
But this can be worked around by submitting a custom schema like the above.

If there is anything I can provide or try out to get this fixed, please let me know and I am happy to help.
